### ISSUE TITLE
A100 No package metadata was found for flashattn-hopper and RuntimeError:The NVIDIA driver on your system is too old (found version 11060)

### ISSUE THREAD

**Issue by pily1** [NVIDIA/Cosmos#48]
export PROMPT="A sleek, humanoid robot stands in a vast warehouse filled with neatly stacked cardboard boxes on industrial shelves. \
The robot's metallic body gleams under the bright, even lighting, highlighting its futuristic design and intricate joints. \
A glowing blue light emanates from its chest, adding a touch of advanced technology. The background is dominated by rows of boxes, \
suggesting a highly organized storage system. The floor is lined with wooden pallets, enhancing the industrial setting. \
The camera remains static, capturing the robot's poised stance amidst the orderly environment, with a shallow depth of \
field that keeps the focus on the robot while subtly blurring the background for a cinematic effect."
root@29122eb0ee69:/workspace# PYTHONPATH=$(pwd) python cosmos1/models/diffusion/inference/text2world.py --checkpoint_dir checkpoints --diffusion_transformer_dir Cosmos-1.0-Diffusion-7B-Text2World --prompt "$PROMPT" --offload_prompt_upsampler --video_save_name Cosmos-1.0-Diffusion-7B-Text2World
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/attention.py", line 104, in <module>
    _flash_attn_v3_version = PkgVersion(get_pkg_version("flashattn-hopper"))
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for flashattn-hopper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/cosmos1/models/diffusion/inference/text2world.py", line 21, in <module>
    from cosmos1.models.diffusion.inference.inference_utils import add_common_arguments, validate_args
  File "/workspace/cosmos1/models/diffusion/inference/inference_utils.py", line 27, in <module>
    from cosmos1.models.diffusion.model.model_t2w import DiffusionT2WModel
  File "/workspace/cosmos1/models/diffusion/model/model_t2w.py", line 26, in <module>
    from cosmos1.models.diffusion.module.blocks import FourierFeatures
  File "/workspace/cosmos1/models/diffusion/module/blocks.py", line 25, in <module>
    from cosmos1.models.diffusion.module.attention import Attention, GPT2FeedForward
  File "/workspace/cosmos1/models/diffusion/module/attention.py", line 20, in <module>
    import transformer_engine as te
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/__init__.py", line 13, in <module>
    from . import pytorch
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/__init__.py", line 73, in <module>
    from transformer_engine.pytorch.attention import DotProductAttention
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/attention.py", line 107, in <module>
    if get_device_compute_capability() == (9, 0) and _NVTE_FLASH_ATTN:
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/utils.py", line 43, in get_device_compute_capability
    props = torch.cuda.get_device_properties(torch.cuda.current_device())
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 940, in current_device
    _lazy_init()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 319, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 11060). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver

**Comment by Midon99** [comment]
Same problem with flashattn-hopper. 
But second part was different. There are 4 GPU in the system and also visible in docker by nvidia-smi
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/cosmos1/models/autoregressive/inference/base.py", line 22, in <module>
    from cosmos1.models.autoregressive.inference.world_generation_pipeline import ARBaseGenerationPipeline
  File "/workspace/cosmos1/models/autoregressive/inference/world_generation_pipeline.py", line 32, in <module>
    from cosmos1.models.autoregressive.diffusion_decoder.inference import diffusion_decoder_process_tokens
  File "/workspace/cosmos1/models/autoregressive/diffusion_decoder/inference.py", line 23, in <module>
    from cosmos1.models.autoregressive.diffusion_decoder.model import LatentDiffusionDecoderModel
  File "/workspace/cosmos1/models/autoregressive/diffusion_decoder/model.py", line 25, in <module>
    from cosmos1.models.diffusion.model.model_t2w import DiffusionT2WModel as VideoDiffusionModel
  File "/workspace/cosmos1/models/diffusion/model/model_t2w.py", line 26, in <module>
    from cosmos1.models.diffusion.module.blocks import FourierFeatures
  File "/workspace/cosmos1/models/diffusion/module/blocks.py", line 25, in <module>
    from cosmos1.models.diffusion.module.attention import Attention, GPT2FeedForward
  File "/workspace/cosmos1/models/diffusion/module/attention.py", line 20, in <module>
    import transformer_engine as te
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/__init__.py", line 13, in <module>
    from . import pytorch
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/__init__.py", line 73, in <module>
    from transformer_engine.pytorch.attention import DotProductAttention
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/attention.py", line 107, in <module>
    if get_device_compute_capability() == (9, 0) and _NVTE_FLASH_ATTN:
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/utils.py", line 43, in get_device_compute_capability
    props = torch.cuda.get_device_properties(torch.cuda.current_device())
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 940, in current_device
    _lazy_init()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 319, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

**Comment by pily1** [comment]
A100 is Ampere architecture,why go to the flashattn-hopper？

**Comment by Midon99** [comment]
Sorry forgot my test was on L40s

**Comment by pily1** [comment]
anyone can help me ?

**Comment by Midon99** [comment]
It is working for me now. I created the docker container again. In principle exactly the same as before, but now it is working.  Strange.

**Comment by sophiahhuang** [comment]
Thank you for your interest in Cosmos. We are glad to hear using the docker container works and will close the issue for now.
